-- (1) SELEIONA TUTTI GLI STUDENTI NATI NEL 1990 (160)
SELECT * 
FROM `students`
WHERE `date_of_birth` LIKE '1990%';

-- (2) SELEZIONA TUTTI I CORSI CHE VALGONO PIU' DI 10 CREDITI (479)
SELECT * 
FROM `courses` 
WHERE `cfu` > 10;

-- (3) SELEZIONARE TUTTI GLI STUDENTI CHE HANNO PIU' DI 30 ANNI
SELECT *
FROM `students`
WHERE `date_of_birth` < DATE_SUB(CURRENT_DATE(), INTERVAL 30 YEAR);

-- (4) SELEZIONARE TUTTI I CORSI DEL PRIMO SEMESTRE DEL PRIMO ANNO DI UN QUALSIASI CORSO DI LAUREA (286)
SELECT *
FROM `courses`
WHERE `period` = 'I semestre' AND `year` = 1;

-- (5) SELEZIONARE TUTTI GLI APPELLI D'ESAME CHE AVVENGONO NEL POMERIGGIO (DOPO LE 14) DEL 20/06/2020 (21)
SELECT *
FROM `exams`
WHERE `date` = '2020-06-20' AND `hour` > '14:00:00';

-- (6) SELEZIONARE TUTTI I CORSI DI LAUREA MAGISTRALE(38)
SELECT * 
FROM `degrees`
WHERE `level` = 'magistrale';

-- (7) DA QUANTI DIPARTIMENTI è COMPOSTO L'UNIVERSITA'?(12)
SELECT COUNT(`id`) AS 'numero_dipartimenti'
FROM `departments`;

-- (8) QUANTI SONO GLI INSEGNANTI CHE NON HANNO UN NUMERO DI TELEFONO?(50)
SELECT *
FROM `teachers`
WHERE `phone` IS NULL;




